# Generated by Django 5.0.7 on 2024-07-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_cartitem_cart_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
